import * as THREE from 'three';
const C = { ground: 0x0b1e2b, block: 0x17364a, block2: 0x1c4660, glass: 0x58c5d4, cyan: 0x55e6df, coral: 0xff7d68, lime: 0xb8e36b, amber: 0xffc46b, road: 0x122a3a, water: 0x0b526b, white: 0xd9f3ee };
const material = (color, options = {}) => new THREE.MeshStandardMaterial({ color, roughness: .78, metalness: .22, ...options });
const mats = { ground: material(C.ground), block: material(C.block), block2: material(C.block2), glass: material(C.glass, { emissive: C.glass, emissiveIntensity: .4, transparent: true, opacity: .82 }), cyan: material(C.cyan, { emissive: C.cyan, emissiveIntensity: 2.4, toneMapped: false }), coral: material(C.coral, { emissive: C.coral, emissiveIntensity: 2.2, toneMapped: false }), lime: material(C.lime, { emissive: C.lime, emissiveIntensity: 1.8, toneMapped: false }), amber: material(C.amber, { emissive: C.amber, emissiveIntensity: 1.8, toneMapped: false }), road: material(C.road), water: material(C.water, { roughness: .2, metalness: .1 }) };
const mesh = (geo, mat, p = [0, 0, 0], r = [0, 0, 0]) => { const m = new THREE.Mesh(geo, mat); m.position.set(...p); m.rotation.set(...r); m.castShadow = true; m.receiveShadow = true; return m; }; const box = (s, mat, p, r) => mesh(new THREE.BoxGeometry(...s), mat, p, r);
function makeLabel(text, color = '#a6fff5') { const c = document.createElement('canvas'); c.width = 512; c.height = 96; const x = c.getContext('2d'); x.fillStyle = '#071623'; x.fillRect(0, 0, c.width, c.height); x.font = '700 30px Arial'; x.fillStyle = color; x.fillText(text, 22, 61); const t = new THREE.CanvasTexture(c); return new THREE.Mesh(new THREE.PlaneGeometry(4.2, .78), new THREE.MeshBasicMaterial({ map: t, transparent: true })); }
function building(group, x, z, w, d, h, mat, label, district) { const root = new THREE.Group(); root.position.set(x, 0, z); root.userData.district = district; const body = box([w, h, d], mat, [0, h / 2, 0]); body.userData = { label, district }; root.add(body); if (h > 9) root.add(box([w * .75, .18, d * .75], mats.glass, [0, h * .68, 0])); if (label) { const sign = makeLabel(label, mat === mats.coral ? '#ffab9c' : '#8ffff2'); sign.position.set(0, h + 1.15, d / 2 + .03); sign.rotation.x = -Math.PI / 2.8; root.add(sign); } group.add(root); return root; }
function road(group, x, z, w, d) { group.add(box([w, .08, d], mats.road, [x, .04, z])); }
export function createCity(scene) {
  const root = new THREE.Group(); scene.add(root); const layers = { landmarks: new THREE.Group(), roads: new THREE.Group(), water: new THREE.Group() }; Object.values(layers).forEach((g) => root.add(g)); const pickables = []; const landmarks = layers.landmarks;
  root.add(box([78, .5, 64], mats.ground, [0, -.3, 0])); layers.water.add(box([78, .12, 11], mats.water, [0, .01, -28])); layers.water.add(box([16, .13, 38], mats.water, [30, .02, -3]));
  for (let x = -30; x <= 30; x += 10) road(layers.roads, x, 0, 2.2, 58); for (let z = -22; z <= 22; z += 10) road(layers.roads, 0, z, 68, 2.2);
  const data = [[-20, -10, 5.5, 5, 18, '平安金融中心', 'FUTIAN', 'coral'], [4, -1, 4.5, 4.5, 22, '京基100', 'LUOHU', 'coral'], [20, 10, 5, 4, 15, '春笋', 'NANSHAN', 'cyan'], [-12, 14, 4, 5, 13, '腾讯滨海', 'NANSHAN', 'cyan'], [14, -14, 4, 4, 12, '市民中心', 'FUTIAN', 'amber'], [-1, 20, 3.5, 3.5, 10, '莲花山', 'FUTIAN', 'lime'], [28, 18, 3, 3, 11, '盐田港', 'YANTIAN', 'blue'], [-28, 10, 3, 3, 9, '前海石公园', 'QIANHAI', 'lime']]; const colorMap = { coral: mats.coral, cyan: mats.cyan, amber: mats.amber, lime: mats.lime, blue: mats.glass };
  data.forEach(([x, z, w, d, h, label, district, color]) => pickables.push(building(landmarks, x, z, w, d, h, colorMap[color], label, district)));
  for (let x = -32; x <= 32; x += 6) for (let z = -20; z <= 22; z += 6) if (Math.random() > .26) { const h = 2.5 + Math.random() * 6; pickables.push(building(landmarks, x + (Math.random() - .5), z + (Math.random() - .5), 3.2, 3.2, h, Math.random() > .5 ? mats.block : mats.block2, '', 'CITY')); }
  for (let x = -34; x <= 34; x += 3) layers.water.add(box([.08, .06, .18], mats.cyan, [x, .12, -22.2])); [['NANSHAN', 18, 20], ['FUTIAN', -12, -14], ['LUOHU', 8, 2], ['QIANHAI', -28, -4], ['YANTIAN', 28, 22]].forEach(([text, x, z]) => { const l = makeLabel(text, '#8faebb'); l.position.set(x, .3, z); l.rotation.x = -Math.PI / 2; root.add(l); });
  const pulse = []; landmarks.traverse((o) => { if (o.material?.emissiveIntensity > 1) pulse.push(o); });
  function focusDistrict(name) { const target = { NANSHAN: [18, 20], 南山: [18, 20], FUTIAN: [-12, -14], 福田: [-12, -14], LUOHU: [8, 2], 罗湖: [8, 2], QIANHAI: [-28, -4], 前海: [-28, -4], YANTIAN: [28, 22], 盐田: [28, 22] }[name] || [0, 0]; window.dispatchEvent(new CustomEvent('city-focus', { detail: { x: target[0], z: target[1] } })); }
  function setMode(mode) { root.userData.mode = mode; if (mode === 'night') { scene.background.set(0x030811); scene.fog.color.set(0x030811); } else { scene.background.set(0x06121d); scene.fog.color.set(0x06121d); } }
  function toggleLayer(layer, visible) { layers[layer].visible = visible; }
  function update(delta, elapsed) { pulse.forEach((o, i) => { if (o.material) o.material.emissiveIntensity = 1.4 + Math.sin(elapsed * 1.8 + i) * .55; }); }
  return { root, layers, pickables, focusDistrict, setMode, toggleLayer, update };
}
